#' Reassign offspring across parents in each cohort.
#'
#' This function will reassign offspring to each parent to ameliorate a common
#' criticism of the genedrop method, that the pedigree is a product of fitness
#' (i.e. "fitter" parents may have "fitter" offspring). This function reassigns
#' offspring to each breeding parent within a cohort. This will preserve the
#' distribution of offspring in mothers and fathers. At present, non-breeding
#' individuals are not sampled as parents.
#'
#' @param ped A pedigree object as generated by check_data
#' @import dplyr
#' @export

# id = unicorn$id
# mother = unicorn$mother
# father = unicorn$father
# cohort = unicorn$cohort
# genotype = unicorn$HornSNP
# ped <- check_data(id, mother, father, cohort, genotype)
# rm(id, mother, father, cohort, genotype)

resample_offspring_func <- function(ped){

  lu_mum <- NULL
  lu_dad <- NULL

  for(h in 1:max(ped$cohort)){

    coparents <- subset(ped, cohort == h)$ID

    lookup_mum <- data.frame(MOTHER = sort(unique(subset(ped, MOTHER %in% coparents)$MOTHER)))

    if(nrow(lookup_mum) > 0){

      if(nrow(lookup_mum) > 1){

        lookup_mum$new.MOTHER <- sample(lookup_mum$MOTHER, replace = F)

      } else {

        lookup_mum$new.MOTHER <- lookup_mum$MOTHER

      }

      lu_mum <- rbind(lu_mum, lookup_mum)
    }

    lookup_dad <- data.frame(FATHER = sort(unique(subset(ped, FATHER %in% coparents)$FATHER)))

    if(nrow(lookup_dad) > 0){

      if(nrow(lookup_dad) > 1){

        lookup_dad$new.FATHER <- sample(lookup_dad$FATHER, replace = F)

      } else {

        lookup_dad$FATHER <- lookup_dad$FATHER

      }

      lu_dad <- rbind(lu_dad, lookup_dad)
    }

    rm(lookup_mum, lookup_dad, coparents)
  }

  suppressMessages(ped <- left_join(ped, lu_mum))
  suppressMessages(ped <- left_join(ped, lu_dad))

  ped$MOTHER <- ped$new.MOTHER
  ped$FATHER <- ped$new.FATHER

  ped[,1:5]

}
